"""empty message

Revision ID: c0e677cf5484
Revises: 66b864b9f735
Create Date: 2022-01-24 22:43:32.530696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0e677cf5484'
down_revision = '66b864b9f735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='role')
    op.drop_table('role')
    op.drop_table('roles_users')
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=100), nullable=True))
    op.drop_index('email', table_name='user')
    op.drop_column('user', 'confirmed_at')
    op.drop_column('user', 'email')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('confirmed_at', mysql.DATETIME(), nullable=True))
    op.create_index('email', 'user', ['email'], unique=False)
    op.drop_column('user', 'role')
    op.drop_column('user', 'name')
    op.create_table('roles_users',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='roles_users_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='roles_users_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'role', ['name'], unique=False)
    # ### end Alembic commands ###
