"""empty message

Revision ID: 4a6d82949664
Revises: 294405e8d426
Create Date: 2022-01-20 23:47:30.867742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6d82949664'
down_revision = '294405e8d426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jjoined_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_jjoined_at'), 'users', ['jjoined_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_jjoined_at'), table_name='users')
    op.drop_column('users', 'jjoined_at')
    # ### end Alembic commands ###
