"""empty message

Revision ID: 91268d33d84b
Revises: a3760d0176e6
Create Date: 2022-01-24 18:52:33.392722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91268d33d84b'
down_revision = 'a3760d0176e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
