"""empty message

Revision ID: a3760d0176e6
Revises: 4a6d82949664
Create Date: 2022-01-20 23:58:40.538044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3760d0176e6'
down_revision = '4a6d82949664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joined_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_jjoined_at', table_name='users')
    op.create_index(op.f('ix_users_joined_at'), 'users', ['joined_at'], unique=False)
    op.drop_column('users', 'jjoined_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jjoined_at', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_users_joined_at'), table_name='users')
    op.create_index('ix_users_jjoined_at', 'users', ['jjoined_at'], unique=False)
    op.drop_column('users', 'joined_at')
    # ### end Alembic commands ###
